name: appimage

on:
  workflow_dispatch:

jobs:
  clang:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: |
          source ./util/ci/common.sh
          install_linux_deps clang gdb ninja-build python3-pip python3-setuptools python3-venv patchelf desktop-file-utils libgdk-pixbuf2.0-dev fakeroot strace fuse sshpass
          sudo wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O /usr/local/bin/appimagetool
          sudo chmod +x /usr/local/bin/appimagetool
          python3 -m venv "$RUNNER_TEMP/appimage-venv"
          "$RUNNER_TEMP/appimage-venv/bin/pip" install --upgrade pip setuptools wheel
          "$RUNNER_TEMP/appimage-venv/bin/pip" install appimage-builder

      - name: Compile AppImage
        run: |
          "$RUNNER_TEMP/appimage-venv/bin/appimage-builder" --recipe misc/AppImageBuilder.yml

      - uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: appimage
          path: ./*.AppImage
          if-no-files-found: error